### ISSUE TITLE
Erro no Menu Dropdown da index.html

### ISSUE THREAD

**Issue by FelipeSantos92Dev** [MariaRita011/projetosprint3#15]
A biblioteca utilizada pelo João no carrossel está entrando em conflito com os nomes das classes utilizadas na Header.
Tentei subir uma atualização com a correção, porém, não possuo permissão para efetuar push no projeto.

A solução é esta:
Onde houver a o nome "dropdown" nas classes, substituir por "dropdownMenu" tanto na index quanto no CSS.

Espero ter ajudado.

**Comment by MariaRita011** [comment]
Bom dia professor Felipe, deu certinho!! Muito obrigada por me acolher e se
disponibilizar para me ajudar, estou muito grata!!💗
